Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.provision "shell", path: "provision.sh"
  config.vm.provision :reload
  config.vbguest.auto_update = true
  config.vm.synced_folder "../../", "/mnt"
end
